version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - torganizer:/var/lib/postgresql/data
    networks:
      - torganizer-network

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "8081:80"
    networks:
      - torganizer-network

volumes: 
  torganizer:

networks: 
  torganizer-network:
    driver: bridge
